version: '3.8'

services:
  events-ms:
    image: postgres:15.3
    restart: always
    container_name: events-ms
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
    - ./postgres:/var/lib/postgresql/data
    ports: 
    - 5438:5432

    